Try to make progress on Pickle errors associated with "db" by making import statements consistent
Currently we're seeing this error:

_pickle.PicklingError: Can't pickle <function db at 0x7fbc846b07c0>: it's not the same object as flask_migrate.cli.db
ERROR:flask_caching:Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/mpsproject/venv/lib/python3.11/site-packages/flask_caching/__init__.py", line 878, in decorated_function
    self.cache.set(
  File "/mpsproject/venv/lib/python3.11/site-packages/cachelib/redis.py", line 83, in set
    dump = self.serializer.dumps(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mpsproject/venv/lib/python3.11/site-packages/cachelib/serializers.py", line 86, in dumps
    return b"!" + pickle.dumps(value, protocol)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

According to https://stackoverflow.com/questions/1412787/picklingerror-cant-pickle-class-decimal-decimal-its-not-the-same-object, this can be caused by inconsistent use of import statements. Pickle requires the class to be imported in the same way everywhere.